// Allocation Strategy types
export const FETCH_ALLOCATION_STRATEGY_DATA = 'FETCH_STRATEGY_DATA';
export const LOADING_ALLOCATION_STRATEGY_DATA = 'LOADING_ALLOCATION_STRATEGY_DATA';
export const CHANGE_ALLOCATION_STRATEGY_VALUE = 'CHANGE_ALLOCATION_STRATEGY_VALUE';
export const CALCULATE_TOTAL_ALLOCATION_STRATEGY = 'CALCULATE_TOTAL_ALLOCATION_STRATEGY';
export const CONFIRM_ALLOCATION_STRATEGY_DATA = 'CONFIRM_ALLOCATION_STRATEGY_DATA';
export const RESET_TOTAL_ALLOCATION_STRATEGY_DATA = 'RESET_TOTAL_ALLOCATION_STRATEGY_DATA';
